---
title: "Document Title"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
    toc_depth: 1
    code_folding: hide
    code_download: yes
  word_document:
    toc: yes
    toc_depth: '1'
---

Last updated: `r format(Sys.Date(), "%B %d %Y")`

See [Package References](https://dr-jt.github.io/semoutput/reference/index.html){target="_blank"} for help documentation on `semoutput` functions

# Setup

Required Packages

```{r setup, message = FALSE}
knitr::opts_chunk$set(error = TRUE, message = FALSE, warning = TRUE)

library(readr)
library(here)
library(dplyr)
library(lavaan)
library(psych)
library(semoutput)
library(semPlot)
library(sjPlot)
```

Import Data

```{r warning=FALSE}
## Import Data
data <- readRDS("../../07_model_new/df_model2.Rds")
```

------------------------------------------------------------------------

------------------------------------------------------------------------

# Descriptives

```{r}
# Prints basic descriptive statistics
sem_descriptives(data)
```

------------------------------------------------------------------------

# Correlation Matrix

```{r}
# Uses sjPlot to print a nice looking correlation table
tab_corr(data, na.deletion = "pairwise", digits = 2, triangle = "lower")
```

------------------------------------------------------------------------

------------------------------------------------------------------------

# EFA {.tabset .tabset-pills}

```{r}
efa_data <- data

## Determine the number of factors to extract
VSS.scree(efa_data)
fa.parallel(efa_data, fa = "fa")
VSS(efa_data, n = 4, rotate = "varimax")

## Conduct EFA analysis with nfactors determined from methods above
efa_fit <- fa(efa_data, fm = "pa", nfactors = 3, rotate = "varimax")
```

## Summary Output

```{r}
efa_method(efa_fit)
efa_var(efa_fit)
efa_loadings(efa_fit)
efa_rotmatrix(efa_fit)
```

## Diagram Output

```{r}
fa.diagram(efa_fit)
```

## Full Output

```{r}
efa_fit
```

------------------------------------------------------------------------

------------------------------------------------------------------------

# CFA {.tabset .tabset-pills}

See the [lavaan Tutorial](https://lavaan.ugent.be/tutorial/index.html){target="_blank"} for model syntax

```{r}
# specify the model
# miro_model7
final_model2 <- "
solution_orientation =~
motivation.welfare.+
benefitForNonAcademy+
impulseForNonAcad.soc.+
targetGroupsGoals.improve.

# ACTORS & NETWORKS
an_transdisciplinary_inv =~
groupsInvolved.civsoc.+
groupsInvolved.citiz.+
natureOfInvolvement.civsoc.+
natureOfInvolvement.citiz.

an_transdisciplinary_goals =~
Impactstatements.emanc. +
Impactstatements.capab.+
targetGroupsGoals.socneeds.+
targetGroupsGoals.socgroups.+
targetGroupsGoals.empower.+
targetGroupsGoals.diversity.

novelty =~
scalabilityRating.out.+
scalabilityRating.up.+
Impactstatements.unknown.+
Impactstatements.unaddressed.+
kindOfChange.pub.


outputs_outcomes =~
concepts3+
impactTargetGroup.pub.+
impactTargetGroup.socgr.+
impactTargetGroup.civsoc.+
adoptByPolicy.rate.+
Impactstatements.mitig.+
Impactstatements.understanding.
"

# fit the model
fit <- cfa(
  final_model2
  , data = data
  , estimator = "WLSMV"
  , mimic = "Mplus"
  # , std.lv = T
  , ordered = T
  )

```

## Summary Output

```{r results='asis'}
sem_tables()
```

## Diagram Output

```{r}
factors <- fit$pta$vnames$lv[[1]]
semPaths(fit, latents = factors, whatLabels = "std", layout = "tree2", 
         rotation = 2, style = "lisrel", optimizeLatRes = TRUE, 
         intercepts = FALSE, residuals = TRUE, curve = 1, curvature = 3, 
         sizeLat = 10, nCharNodes = 8, sizeMan = 11, sizeMan2 = 4, 
         edge.label.cex = 1.2, edge.color = "#000000")
```

## Residual Correlation Matrix

```{r}
sem_residuals(fit)
```

## Full Output

### Summary

```{r}
summary(fit, fit.measures = TRUE, standardized = TRUE)
```

### Parameter Estimates

```{r}
standardizedSolution(fit)
```

### Modification Indices

```{r}
modificationIndices(fit, sort. = TRUE, minimum.value = 3)
```

------------------------------------------------------------------------

------------------------------------------------------------------------

# SEM {.tabset .tabset-pills}

See the [lavaan Tutorial](https://lavaan.ugent.be/tutorial/index.html){target="_blank"} for model syntax

```{r}
# specify the model
model <- '
# latent factors


# variances


# covariances


# regressions

'
# fit the model
fit <- sem(model = model, data = data, mimic = "lavaan", 
           estimator = "ML", missing = "ML", 
           std.lv = FALSE, std.ov = FALSE, test = "standard", 
           se = "standard", bootstrap = "standard")
```

## Summary Output

```{r results='asis'}
sem_tables()
```

## Diagram Output

```{r}
factors <- fit$pta$vnames$lv[[1]]
semPaths(fit, latents = factors, whatLabels = "std", layout = "tree2", 
         rotation = 2, style = "lisrel", optimizeLatRes = TRUE, 
         intercepts = FALSE, residuals = TRUE, curve = 1, curvature = 3, 
         sizeLat = 10, nCharNodes = 8, sizeMan = 11, sizeMan2 = 4, 
         edge.label.cex = 1.2, edge.color = "#000000")
```

## Residual Correlation Matrix

```{r}
sem_residuals(fit)
```

## Full Output

### Summary

```{r}
summary(fit, fit.measures = TRUE, standardized = TRUE)
```

### Parameter Estimates

```{r}
standardizedSolution(fit)
```

### Modification Indices

```{r}
modificationIndices(fit, sort. = TRUE, minimum.value = 3)
```

------------------------------------------------------------------------

------------------------------------------------------------------------

# Session Info

```{r comment=""}
citation("lavaan")
citation()
sessionInfo()
```
